apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    compileSdkVersion 34

    namespace 'jp.dds.wpnavi'

    defaultConfig {
        applicationId "jp.dds.wpnavi"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        disable 'MissingTranslation'
    }

    task('incrementVersionCode') {
        doLast {
            exec {
                commandLine 'cscript', 'd:/dds/bin/scripter.wsf', '-w', '../../set_git_version.pl', 'src/main/AndroidManifest.xml'
            }
        }
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

tasks.configureEach { task ->
    if (task.name == 'generateReleaseBuildConfig') {
        task.dependsOn 'incrementVersionCode'
    }
}

dependencies {
    implementation project(':dds_lib')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    implementation 'androidx.core:core-ktx:1.12.0'
}
